version: '3.5'

services:
    redis:
        image: redis:6.2.6
        command: redis-server --appendonly yes
        volumes:
            - redis:/data

    minio:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: 'AKIAIOSFODNN7EXAMPLE' # or any user name you like , this will be used to log in to minio dashboard
            MINIO_ROOT_PASSWORD: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
        command: ['server', '/data', '--console-address', ':9001']
        volumes:
            - minio:/data
    mysql:
        image: mysql:latest
        container_name: iso-rest-mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_PASSWORD: password
        ports:
            - '3306:3306'
        volumes:
            - dbdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: iso-rest-phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 300M
        restart: always
        ports:
            - 8083:80
    mongo:
        # can be replace by ghcr.io/appvantageasia/mongo-entreprise:X.X.X
        # changes to be done in override file
        image: mongo:5.0.6
        container_name: iso-rest-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo:/data/db
        networks:
            - mongo-compose-network

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: iso-rest-mongo
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: password

        ports:
            - 8081:8081
        links:
            - mongo
        depends_on:
            - mongo
        networks:
            - mongo-compose-network

volumes:
    dbdata:
    redis:
    mysql_data:
        driver: local
    phpmyadmin_data:
        driver: local
    mongo:
    minio:
        driver: local
networks:
    mongo-compose-network:
        driver: bridge
